server:
  port: 8030
#应用名称 （nacos会将该名称当做服务名称）
spring:
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
stock-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.yunshi.ribbon.rule.CustomRule
ribbon:
 eager-load:
   enabled: true
   clients: stock-service


